/*
 * Swagger Blog
 *
 * A Simple Blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Body2 struct {

	Content string `json:"content,omitempty"`

	Tags []string `json:"tags,omitempty"`

	Name string `json:"name,omitempty"`

	Token string `json:"token,omitempty"`
}
