/*
 * Swagger Blog
 *
 * A Simple Blog
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v3/",
		Index,
	},

	Route{
		"GetArticleById",
		strings.ToUpper("Get"),
		"/v3/article/{id}",
		GetArticleById,
	},

	Route{
		"GetArticlesOfUser",
		strings.ToUpper("Get"),
		"/v3/articles/{username}",
		GetArticlesOfUser,
	},

	Route{
		"GetCommentsOfArticle",
		strings.ToUpper("Get"),
		"/v3/article/{id}/comments",
		GetCommentsOfArticle,
	},

	Route{
		"ChangePassword",
		strings.ToUpper("Put"),
		"/v3/user/{username}",
		ChangePassword,
	},

	Route{
		"CreateArticle",
		strings.ToUpper("Post"),
		"/v3/user/{username}/article",
		CreateArticle,
	},

	Route{
		"CreateComment",
		strings.ToUpper("Post"),
		"/v3/user/{username}/article/{id}/comment",
		CreateComment,
	},

	Route{
		"SignIn",
		strings.ToUpper("Post"),
		"/v3/user/{username}",
		SignIn,
	},

	Route{
		"SignUp",
		strings.ToUpper("Post"),
		"/v3/user",
		SignUp,
	},
}
